version: '3.8'
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo-prod:/data/db
    env_file:
      - ./config/production.env

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile.production
    ports:
      - "80:80"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.production
    ports:
      - "5000:5000"

    depends_on:
      - mongodb
    env_file:
      - ./config/development.env

volumes:
  mongo-prod:


